#!/bin/bash

cd ~
sudo yum update -y
sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
#sudo wget -O /etc/yum.repos.d/jenkins.repo
sudo rpm --import http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key
#sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key

sudo yum install git -y
sudo yum install jenkins -y

sudo service jenkins start
sudo service jenkins stop

sudo rm -R /var/lib/jenkins/*

sudo aws s3 cp s3://tfjenkinsconf /var/lib/jenkins --recursive

sudo chown -R jenkins:jenkins /var/lib/jenkins

sudo service jenkins start

echo `sudo service jenkins status`
